"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProfileCardStyled = void 0;
var styled_components_1 = __importDefault(require("styled-components"));
exports.ProfileCardStyled = styled_components_1.default.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n\tdisplay: flex;\n\twidth: ", ";\n\theight: ", ";\n\tcolor: ", ";\n\tborder-radius: 12px;\n\tfont-family: Roboto, \"Noto Sans KR\", sans-serif;\n\tbox-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);\n\toverflow: hidden;\n\tbox-sizing: border-box;\n\tmargin: 0 auto;\n\tcursor: pointer;\n\n\t.left {\n\t\twidth: 50%;\n\t\timg {\n\t\t\twidth: 100%;\n\t\t\theight: 100%;\n\t\t\tobject-fit: cover;\n\t\t}\n\t}\n\t.right {\n\t\twidth: 50%;\n\t\tdisplay: flex;\n\t\tflex-direction: column;\n\t\tjustify-content: space-around;\n\t\tpadding: 0 40px;\n\t}\n\n\t.name {\n\t\tfont-size: 24px;\n\t\tfont-weight: bold;\n\t\tmargin: 0;\n\t}\n\n\t.id {\n\t\tfont-size: 16px;\n\t\topacity: 0.5;\n\t}\n\n\t.naming {\n\t\ttext-align: center;\n\t}\n\n\t.infos {\n\t\tdisplay: flex;\n\t\tjustify-content: space-around;\n\t\talign-items: center;\n\t}\n\n\t.info {\n\t\tdisplay: flex;\n\t\tjustify-content: center;\n\t\talign-items: center;\n\t\tflex-direction: column;\n\t}\n\n\t.info_title {\n\t\tfont-size: 16px;\n\t\topacity: 0.5;\n\t}\n\n\t.info_count {\n\t\tfont-size: 20px;\n\t\tmargin-top: 5px;\n\t}\n\n\t.introduce {\n\t\tmargin: 0;\n\t\tword-wrap: break-word;\n\t\tdisplay: -webkit-box;\n\t\t-webkit-line-clamp: 3;\n\t\t-webkit-box-orient: vertical;\n\t\toverflow: hidden;\n\t\ttext-align: center;\n\t\tline-height: 1.3;\n\t}\n"], ["\n\tdisplay: flex;\n\twidth: ", ";\n\theight: ", ";\n\tcolor: ", ";\n\tborder-radius: 12px;\n\tfont-family: Roboto, \"Noto Sans KR\", sans-serif;\n\tbox-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);\n\toverflow: hidden;\n\tbox-sizing: border-box;\n\tmargin: 0 auto;\n\tcursor: pointer;\n\n\t.left {\n\t\twidth: 50%;\n\t\timg {\n\t\t\twidth: 100%;\n\t\t\theight: 100%;\n\t\t\tobject-fit: cover;\n\t\t}\n\t}\n\t.right {\n\t\twidth: 50%;\n\t\tdisplay: flex;\n\t\tflex-direction: column;\n\t\tjustify-content: space-around;\n\t\tpadding: 0 40px;\n\t}\n\n\t.name {\n\t\tfont-size: 24px;\n\t\tfont-weight: bold;\n\t\tmargin: 0;\n\t}\n\n\t.id {\n\t\tfont-size: 16px;\n\t\topacity: 0.5;\n\t}\n\n\t.naming {\n\t\ttext-align: center;\n\t}\n\n\t.infos {\n\t\tdisplay: flex;\n\t\tjustify-content: space-around;\n\t\talign-items: center;\n\t}\n\n\t.info {\n\t\tdisplay: flex;\n\t\tjustify-content: center;\n\t\talign-items: center;\n\t\tflex-direction: column;\n\t}\n\n\t.info_title {\n\t\tfont-size: 16px;\n\t\topacity: 0.5;\n\t}\n\n\t.info_count {\n\t\tfont-size: 20px;\n\t\tmargin-top: 5px;\n\t}\n\n\t.introduce {\n\t\tmargin: 0;\n\t\tword-wrap: break-word;\n\t\tdisplay: -webkit-box;\n\t\t-webkit-line-clamp: 3;\n\t\t-webkit-box-orient: vertical;\n\t\toverflow: hidden;\n\t\ttext-align: center;\n\t\tline-height: 1.3;\n\t}\n"])), function (props) { return props.width; }, function (props) { return props.height; }, function (props) { return props.color; });
var templateObject_1;
